# Generated by Django 5.1.7 on 2025-03-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='total_buy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
